### ISSUE TITLE
Bot looks for DB_FILE in .env

### ISSUE THREAD

**Issue by SobakaPirat** [dnulyb/piwo-bot#1]
I have an error `Key DB_FILE not found in .\piwo-bot-main\.env`

**Comment by SobakaPirat** [comment]
I assume it should be like `DB_FILE = 'Main_DB.sql'`, but what is `team.sql` for?

**Comment by dnulyb** [comment]
Fixed in commit 7ea51e1.

> I assume it should be like `DB_FILE = 'Main_DB.sql'`, but what is `team.sql` for?

```DB_FILE``` is the ```.sqlite``` database file, set it like so: ```DB_FILE = "db_name.sqlite"```
```team.sql``` contains the SQLite schema that will be used to build the database tables if they do not already exist.
